### PR TITLE
Code organization

### PR DESCRIPTION
**Pull request by alvarosan**

### CODE REVIEW

**Comment by alvarosan** [comment]
@johnkit ,  these changes will require also a (this)[https://gitlab.kitware.com/john.tourtellott/internal-databrowser/merge_requests/13] patch for databrowser.

**Comment by alvarosan** [comment]
@johnkit ,  I tried it with the superbuild and it works.   Only needed to enable some of the extensions so that DataBrowser builds.  There is a [merge request](https://gitlab.kitware.com/john.tourtellott/internal-es-superbuild/merge_requests/2) in es-superbuild.

**Comment by johnkit** [comment]
@alvarosan  This looks great to me. There is one thing:

* You updated the CMake requirement to 3.9, whereas the rest of CMB builds with 3.8.2. Is there something specific we need in 3.9, or were you just updating to the latest version?

**Comment by alvarosan** [comment]
Just updated to the latest version, I did not realize CMB's requirement was 3.8.2, I will make vtkMap match that version too.

**Comment by alvarosan** [comment]
@johnkit , changed CMake version required to 3.8.2.

**Pull request merged**
