### PR TITLE
Support polygon selection style

### PR DESCRIPTION
**Pull request by alvarosan**

### CODE REVIEW

**Comment by alvarosan** [comment]
Ready to merge @johnkit .  Make sure you update databrowser with this [branch](https://gitlab.kitware.com/john.tourtellott/internal-databrowser/merge_requests/10) after this is merged,  otherwise DataBrowser would not build with this vtkMap.

**Comment by alvarosan** [comment]
Added your fixes @johnkit , you can go ahead and merge it (I can merge it if you give me access to the main repository).

**Comment by johnkit** [comment]
@aashish24 Would you please add @alvarosan as a collaborator on this project?

**Comment by aashish24** [comment]
done @alvarosan should have got an invite

**Comment by alvarosan** [comment]
Thanks @aashish24 and @johnkit

**Pull request merged**
