### PR TITLE
Marker labels

### PR DESCRIPTION
**Pull request by alvarosan**
labeled-markers

### CODE REVIEW

**Comment by alvarosan** [comment]
Labels should display similarly in DataBrowser by default, but I also exposed API in the MarkerSet to adjust text properties and offset.

**Comment by alvarosan** [comment]
Don't merge yet, I want to include still a tiny patch.

**Comment by alvarosan** [comment]
Done, I think we could merge this, the data-browser patch is [here](https://gitlab.kitware.com/john.tourtellott/internal-databrowser/merge_requests/22).

**Comment by alvarosan** [comment]
Added your fixes @johnkit .

**Comment by johnkit** [comment]
+1

I definitely don't understand it all, but it builds/works on mac. Please go ahead and merge. Thanks.

**Pull request merged**
